<script setup lang="ts">
import { ref } from 'vue'
import { Card } from '../types/index'
defineProps<{data: Card}>()

</script>

<template>

<div class="relative flex min-h-screen flex-col justify-center overflow-hidden bg-gray-50 py-6 sm:py-8 px-10" id="inner-card">
  <div class="absolute inset-0 bg-[url(/img/grid.svg)] bg-center [mask-image:linear-gradient(180deg,white,rgba(255,255,255,0))]" ></div>
  <div class="relative bg-white  shadow-xl ring-1 ring-gray-900/5  sm:rounded-lg" >
    <div class="mx-10 mt-8 mb-8" >
      <div class="text-5xl  font-mono text-gray-400">Story {{data.id}} </div>
      <div class="divide-y divide-gray-300/50">
        <div class="space-y-6 py-8 pt-6 text-base leading-7">
          <p class="text-2xl font-semibold">{{data.title}}</p>
          <ul class="space-y-4">
            <li class="flex items-center">
              <svg class="h-6 w-6 flex-none fill-sky-100 stroke-sky-500 stroke-2" stroke-linecap="round" stroke-linejoin="round">
                <circle cx="12" cy="12" r="11" />
                <path d="m8 13 2.165 2.165a1 1 0 0 0 1.521-.126L16 9" fill="none" />
              </svg>
              <p class="ml-4">
               <b>As</b> {{data.AsAn}}
              </p>
            </li>
            <li class="flex items-center">
              <svg class="h-6 w-6 flex-none fill-sky-100 stroke-sky-500 stroke-2" stroke-linecap="round" stroke-linejoin="round">
                <circle cx="12" cy="12" r="11" />
                <path d="m8 13 2.165 2.165a1 1 0 0 0 1.521-.126L16 9" fill="none" />
              </svg>
              <p class="ml-4">
               <b>I want to</b> {{data.IWantTo}}
              </p>
            </li>
            <li class="flex items-center">
              <svg class="h-6 w-6 flex-none fill-sky-100 stroke-sky-500 stroke-2" stroke-linecap="round" stroke-linejoin="round">
                <circle cx="12" cy="12" r="11" />
                <path d="m8 13 2.165 2.165a1 1 0 0 0 1.521-.126L16 9" fill="none" />
              </svg>
              <p class="ml-4"><b>So that</b> {{data.SoThat}} </p>
            </li>
          </ul>
          <div class="text-xl font-semibold">Acceptance Criteria</div>
          <p>{{data.AcceptanceCriteria}}</p>
        </div>
        <div class="pt-6 text-base font-semibold leading-7">
          <span class= "text-xl mr-4" :class="data.State == 'Rejected'?'text-red-500':'text-green-500'">{{data.State}}</span>
          <span :class="data.State == 'Rejected'?'text-red-400':'text-green-400'">{{data.Reason}}</span>
          <div class="relative text-sm text-gray-200 text-right font-bold"> @Generated by storycard.lawted.tech</div>
        </div>
      </div>
    </div>
  </div>
</div>

</template>

<style scoped>

</style>
